apiVersion: apps/v1
kind: Deployment
metadata:
  name: RegisterMaster
  labels:
    app: RegisterMaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: RegisterMaster
  template:
    metadata:
      labels:
        app: RegisterMaster
    spec:
      containers:
        - name: RegisterMaster
          image: username/RegisterMaster:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5