server:
  port: 8080

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: Registration
          uri: http://localhost:8081
          predicates:
            - Path=/registrations/** 
        - id: Payment
          uri: http://localhost:8082
          predicates:
            - Path=/pays/** 
        - id: RegisterMaster
          uri: http://localhost:8083
          predicates:
            - Path=/registerMasters/** 
        - id: dashboard
          uri: http://localhost:8084
          predicates:
            - Path= /dashboards/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: Registration
          uri: http://Registration:8080
          predicates:
            - Path=/registrations/** 
        - id: Payment
          uri: http://Payment:8080
          predicates:
            - Path=/pays/** 
        - id: RegisterMaster
          uri: http://RegisterMaster:8080
          predicates:
            - Path=/registerMasters/** 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path= /dashboards/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080