server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: apply
          uri: http://localhost:8081
          predicates:
            - Path=/applies/** 
        - id: payment
          uri: http://localhost:8082
          predicates:
            - Path=/pays/** 
        - id: applymanager
          uri: http://localhost:8083
          predicates:
            - Path=/applyManagers/** 
        - id: dashboard
          uri: http://localhost:8084
          predicates:
            - Path= /dashboards/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: apply
          uri: http://apply:8080
          predicates:
            - Path=/applies/** 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/pays/** 
        - id: applymanager
          uri: http://applymanager:8080
          predicates:
            - Path=/applyManagers/** 
        - id: dashboard
          uri: http://dashboard:8080
          predicates:
            - Path= /dashboards/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080