apiVersion: apps/v1
kind: Deployment
metadata:
  name: applymanager
  labels:
    app: applymanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: applymanager
  template:
    metadata:
      labels:
        app: applymanager
    spec:
      containers:
        - name: applymanager
          image: username/applymanager:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5